export enum GrammarName {
    VERBS = 'verbes',
    ADVERBS = 'adverbes',
    ADJECTIVES = 'adjectifs',
    PHRASES = 'expressions',
    CONJUNCTIONS = 'conjonctions',
    NOUNS = 'noms',
    VERB = 'verbe',
    ADVERB = 'adverbe',
    ADJECTIVE = 'adjectif',
    PHRASE = 'expression',
    CONJUNCTION = 'conjonction',
    NOUN = 'nom',
    VERBSTITEL = 'verbes',
    ADVERBSTITEL = 'adverbes',
    ADJECTIVESTITEL = 'adjectifs',
    PHRASESTITEL = 'expressions',
    CONJUNCTIONSTITEL = 'conjonctions',
    NOUNSTITEL = 'noms'
}
