image: node:8.12.0

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@6.2.1
  - npm install
  - ng build
  - mkdir -p public
  - mv dist/vocabulary/* public/
  artifacts:
    paths:
    - public
  only:
  - refacto
  - pages
